- hosts: all
  gather_facts: yes
  tasks:
    - name: copy from control node to managed node
      copy:
        src: /home/shakthi/file1
        dest: /tmp/test.txt
        owner: shakthi
        group: mahi
        mode: u=rw,g=r,o=r
      tags: copy_file