- name: Build and Run Custom Docker Image
  hosts: web
  become: true
  tasks:

    - name: Create build directory on remote
      file:
        path: /opt/custom-nginx
        state: directory

    - name: Copy Dockerfile
      copy:
        src: app/Dockerfile
        dest: /opt/custom-nginx/Dockerfile

    - name: Copy index.html
      copy:
        src: app/index.html
        dest: /opt/custom-nginx/index.html

    - name: Build Docker image
      command: docker build -t mynginx:latest /opt/custom-nginx
      args:
        chdir: /opt/custom-nginx

    - name: Run Docker container
      docker_container:
        name: mynginx
        image: mynginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:82"